# Generated by Django 5.2.1 on 2025-10-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0022_bankaccountmodel_financial_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(choices=[('Assets', [('asset_ca_cash', 'Current Asset'), ('asset_ca_mkt_sec', 'Marketable Securities'), ('asset_ca_recv', 'Receivables'), ('asset_ca_inv', 'Inventory'), ('asset_ca_uncoll', 'Uncollectibles'), ('asset_ca_prepaid', 'Prepaid'), ('asset_ca_other', 'Other Liquid Assets'), ('asset_lti_notes', 'Notes Receivable'), ('asset_lti_land', 'Land'), ('asset_lti_sec', 'Securities'), ('asset_ppe_build', 'Buildings'), ('asset_ppe_build_accum_depr', 'Buildings - Accum. Depreciation'), ('asset_ppe_plant', 'Plant'), ('asset_ppe_plant_depr', 'Plant - Accum. Depreciation'), ('asset_ppe_equip', 'Equipment'), ('asset_ppe_equip_accum_depr', 'Equipment - Accum. Depreciation'), ('asset_ia', 'Intangible Assets'), ('asset_ia_accum_amort', 'Intangible Assets - Accum. Amortization'), ('asset_adjustment', 'Other Assets')]), ('Liabilities', [('lia_cl_acc_payable', 'Accounts Payable'), ('lia_cl_wages_payable', 'Wages Payable'), ('lia_cl_int_payable', 'Interest Payable'), ('lia_cl_taxes_payable', 'Taxes Payable'), ('lia_cl_st_notes_payable', 'Short Term Notes Payable'), ('lia_cl_ltd_mat', 'Current Maturities of Long Term Debt'), ('lia_cl_def_rev', 'Deferred Revenue'), ('lia_cl_other', 'Other Liabilities'), ('lia_ltl_notes', 'Long Term Notes Payable'), ('lia_ltl_bonds', 'Bonds Payable'), ('lia_ltl_mortgage', 'Mortgage Payable')]), ('Equity', [('eq_capital', 'Capital'), ('eq_stock_common', 'Common Stock'), ('eq_stock_preferred', 'Preferred Stock'), ('eq_adjustment', 'Other Equity Adjustments'), ('eq_dividends', 'Dividends & Distributions to Shareholders'), ('in_operational', 'Operational Income'), ('in_passive', 'Investing/Passive Income'), ('in_interest', 'Interest Income'), ('in_gain_loss', 'Capital Gain/Loss Income'), ('in_other', 'Other Income'), ('cogs_regular', 'Cost of Goods Sold'), ('ex_regular', 'Regular Expense'), ('ex_interest_st', 'Interest Expense - Short Term Debt'), ('ex_interest', 'Interest Expense - Long Term Debt'), ('ex_taxes', 'Tax Expense'), ('ex_capital', 'Capital Expense'), ('ex_depreciation', 'Depreciation Expense'), ('ex_amortization', 'Amortization Expense'), ('ex_other', 'Other Expense')]), ('Root', [('root_coa', 'CoA Root Account'), ('root_assets', 'Assets Root Account'), ('root_liabilities', 'Liabilities Root Account'), ('root_capital', 'Capital Root Account'), ('root_income', 'Income Root Account'), ('root_cogs', 'COGS Root Account'), ('root_expenses', 'Expenses Root Account')])], max_length=30, verbose_name='Account Role'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='role_default',
            field=models.BooleanField(blank=True, null=True, verbose_name='CoA Role Default Account'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
        migrations.AlterField(
            model_name='entityunitmodel',
            name='document_prefix',
            field=models.CharField(max_length=3, verbose_name='Document Prefix'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='vendor_name',
            field=models.CharField(max_length=100, verbose_name='Vendor Name'),
        ),
    ]
