# Generated by Django 5.2.1 on 2025-08-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0022_bankaccountmodel_financial_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='vendor_name',
            field=models.CharField(max_length=100, verbose_name='Vendor Name'),
        ),
    ]
