# Generated by Django 5.2.1 on 2025-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0023_alter_customermodel_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(choices=[('Activos', [('asset_ca_cash', 'Activo actual'), ('asset_ca_mkt_sec', 'Valores negociables'), ('asset_ca_recv', 'Créditos'), ('asset_ca_inv', 'Inventario'), ('asset_ca_uncoll', 'Incobrables'), ('asset_ca_prepaid', 'Prepagos'), ('asset_ca_other', 'Otros activos líquidos'), ('asset_lti_notes', 'Notas por cobrar'), ('asset_lti_land', 'Terrenos'), ('asset_lti_sec', 'Valores'), ('asset_ppe_build', 'Edificios'), ('asset_ppe_build_accum_depr', 'Edificios - depreciación acumulada'), ('asset_ppe_plant', 'Planta'), ('asset_ppe_plant_depr', 'Planta - depreciación acumulada'), ('asset_ppe_equip', 'Equipo'), ('asset_ppe_equip_accum_depr', 'Equipo - depreciación acumulada'), ('asset_ia', 'Activos intangibles'), ('asset_ia_accum_amort', 'Activos intangibles - amortización acumulada'), ('asset_adjustment', 'Otros activos')]), ('Pasivos', [('lia_cl_acc_payable', 'Cuentas por pagar'), ('lia_cl_wages_payable', 'Salarios por pagar'), ('lia_cl_int_payable', 'Intereses por pagar'), ('lia_cl_taxes_payable', 'Impuestos por pagar'), ('lia_cl_st_notes_payable', 'Pagarés a corto plazo'), ('lia_cl_ltd_mat', 'Vencimientos actuales de deuda a largo plazo'), ('lia_cl_def_rev', 'Ingresos diferidos'), ('lia_cl_other', 'Otros pasivos'), ('lia_ltl_notes', 'Pagarés a largo plazo'), ('lia_ltl_bonds', 'Bonos por pagar'), ('lia_ltl_mortgage', 'Hipotecas por pagar')]), ('Patrimonio', [('eq_capital', 'Capital'), ('eq_stock_common', 'Acciones ordinarias'), ('eq_stock_preferred', 'Acciones preferentes'), ('eq_adjustment', 'Otros ajustes de capital'), ('eq_dividends', 'Dividendos y distribuciones para accionistas'), ('in_operational', 'Ingresos operativos'), ('in_passive', 'Ingresos pasivos / de inversión'), ('in_interest', 'Ingresos por interés'), ('in_gain_loss', 'Ingresos por ganancias / pérdidas de capital'), ('in_other', 'Otros ingresos'), ('cogs_regular', 'Costos de bienes vendidos'), ('ex_regular', 'Gastos regulares'), ('ex_interest_st', 'Gastos por intereses - Deuda a corto plazo'), ('ex_interest', 'Gastos por intereses - Deuda a largo plazo'), ('ex_taxes', 'Gastos fiscales'), ('ex_capital', 'Gastos de capital'), ('ex_depreciation', 'Gastos de depreciación'), ('ex_amortization', 'Gastos de amortización'), ('ex_other', 'Otros gastos')]), ('Root', [('root_coa', 'CoA Root Account'), ('root_assets', 'Assets Root Account'), ('root_liabilities', 'Liabilities Root Account'), ('root_capital', 'Capital Root Account'), ('root_income', 'Income Root Account'), ('root_cogs', 'COGS Root Account'), ('root_expenses', 'Expenses Root Account')])], max_length=30, verbose_name='Account Role'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='role_default',
            field=models.BooleanField(blank=True, null=True, verbose_name='CoA Role Default Account'),
        ),
    ]
